CREATE TABLE chat_participants
(
    chat_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_chat_participants PRIMARY KEY (chat_id, user_id)
);

CREATE TABLE chats
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type     VARCHAR(255),
    event_id BIGINT,
    CONSTRAINT pk_chats PRIMARY KEY (id)
);

CREATE TABLE dog_photo_urls
(
    dog_id     BIGINT NOT NULL,
    photo_urls VARCHAR(255)
);

CREATE TABLE dogs
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    breed          VARCHAR(255),
    birthdate      date                                    NOT NULL,
    size           VARCHAR(255)                            NOT NULL,
    gender         VARCHAR(255)                            NOT NULL,
    personality    VARCHAR(255)                            NOT NULL,
    activity_level VARCHAR(255)                            NOT NULL,
    about          VARCHAR(255),
    owner_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_dogs PRIMARY KEY (id)
);

CREATE TABLE event_participants
(
    event_id  BIGINT NOT NULL,
    user_id   BIGINT NOT NULL,
    status    VARCHAR(255),
    joined_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_event_participants PRIMARY KEY (event_id, user_id)
);

CREATE TABLE events
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title           VARCHAR(255),
    description     VARCHAR(255),
    event_date_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    location        GEOGRAPHY(POINT, 4326),
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    host_id         BIGINT                                  NOT NULL,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

CREATE TABLE languages
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code VARCHAR(255)                            NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_languages PRIMARY KEY (id)
);

CREATE TABLE matches
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user1_id   BIGINT                                  NOT NULL,
    user2_id   BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_matches PRIMARY KEY (id)
);

CREATE TABLE messages
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content   VARCHAR(255),
    timestamp TIMESTAMP WITHOUT TIME ZONE,
    chat_id   BIGINT                                  NOT NULL,
    sender_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_messages PRIMARY KEY (id)
);

CREATE TABLE payments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount    DOUBLE PRECISION,
    currency  VARCHAR(255),
    status    VARCHAR(255),
    timestamp TIMESTAMP WITHOUT TIME ZONE,
    user_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_payments PRIMARY KEY (id)
);

CREATE TABLE preferences
(
    user_id                  BIGINT NOT NULL,
    preferred_personality    VARCHAR(255),
    preferred_activity_level VARCHAR(255),
    preferred_size           VARCHAR(255),
    preferred_gender         VARCHAR(255),
    CONSTRAINT pk_preferences PRIMARY KEY (user_id)
);

CREATE TABLE roles
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(20)                              NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE services
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255),
    type      VARCHAR(255),
    latitude  DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    rating    DOUBLE PRECISION,
    CONSTRAINT pk_services PRIMARY KEY (id)
);

CREATE TABLE swipes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    liker_id   BIGINT                                  NOT NULL,
    target_id  BIGINT                                  NOT NULL,
    decision   VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_swipes PRIMARY KEY (id)
);

CREATE TABLE user_languages
(
    language_id BIGINT NOT NULL,
    user_id     BIGINT NOT NULL,
    CONSTRAINT pk_user_languages PRIMARY KEY (language_id, user_id)
);

CREATE TABLE user_roles
(
    role_id INTEGER NOT NULL,
    user_id BIGINT  NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

CREATE TABLE users
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username          VARCHAR(255)                            NOT NULL,
    email             VARCHAR(255)                            NOT NULL,
    password_hash     VARCHAR(255)                            NOT NULL,
    bio               VARCHAR(255),
    birthdate         date,
    gender            VARCHAR(255),
    location          GEOGRAPHY(POINT, 4326),
    location_visible  BOOLEAN,
    profile_photo_url VARCHAR(255),
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE swipes
    ADD CONSTRAINT uc_ab230e7388d33c4a9049d5c30 UNIQUE (liker_id, target_id);

ALTER TABLE languages
    ADD CONSTRAINT uc_languages_code UNIQUE (code);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_name UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE chats
    ADD CONSTRAINT FK_CHATS_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id);

ALTER TABLE chat_participants
    ADD CONSTRAINT FK_CHAT_PARTICIPANTS_ON_CHAT FOREIGN KEY (chat_id) REFERENCES chats (id);

ALTER TABLE chat_participants
    ADD CONSTRAINT FK_CHAT_PARTICIPANTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE dogs
    ADD CONSTRAINT FK_DOGS_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (id);

ALTER TABLE events
    ADD CONSTRAINT FK_EVENTS_ON_HOST FOREIGN KEY (host_id) REFERENCES users (id);

ALTER TABLE event_participants
    ADD CONSTRAINT FK_EVENT_PARTICIPANTS_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id);

ALTER TABLE event_participants
    ADD CONSTRAINT FK_EVENT_PARTICIPANTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE matches
    ADD CONSTRAINT FK_MATCHES_ON_USER1 FOREIGN KEY (user1_id) REFERENCES users (id);

ALTER TABLE matches
    ADD CONSTRAINT FK_MATCHES_ON_USER2 FOREIGN KEY (user2_id) REFERENCES users (id);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_CHAT FOREIGN KEY (chat_id) REFERENCES chats (id);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_SENDER FOREIGN KEY (sender_id) REFERENCES users (id);

ALTER TABLE payments
    ADD CONSTRAINT FK_PAYMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE preferences
    ADD CONSTRAINT FK_PREFERENCES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE swipes
    ADD CONSTRAINT FK_SWIPES_ON_LIKER FOREIGN KEY (liker_id) REFERENCES users (id);

ALTER TABLE swipes
    ADD CONSTRAINT FK_SWIPES_ON_TARGET FOREIGN KEY (target_id) REFERENCES users (id);

ALTER TABLE dog_photo_urls
    ADD CONSTRAINT fk_dog_photourls_on_dog FOREIGN KEY (dog_id) REFERENCES dogs (id);

ALTER TABLE user_languages
    ADD CONSTRAINT fk_uselan_on_language FOREIGN KEY (language_id) REFERENCES languages (id);

ALTER TABLE user_languages
    ADD CONSTRAINT fk_uselan_on_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (id);